### ISSUE TITLE
Adding manga from MangaRock is not working

### ISSUE THREAD

**Issue by janowskima** [poketo/poketo-reader#42]
The title says it all. The error is as follows:

![adnotacja 2018-12-29 151851](https://user-images.githubusercontent.com/45448231/50539234-1e60f900-0b7d-11e9-8c83-d36f557236ec.jpg)

**Comment by rosszurowski** [comment]
Thanks for reporting this.

MangaRock blocks access to series in countries where they've been licensed. It looks like if you try to access this series from a US-based IP address you'll see this error:

<img width="809" alt="screen shot 2018-12-30 at 21 24 43" src="https://user-images.githubusercontent.com/303731/50547225-6bc29080-0c79-11e9-920e-94320417f97d.png">

I suspect that some US company has licensed this series for publishing, so they've restricted access to it for US viewers. Unfortunately, Poketo's server-side code runs in the US, so there's no easy way around this.

The bad news is you won't be able to read it on MangaRock through Poketo. The good news is you (a) might now be able to find an English version of this series available for purchase somewhere, which will help support the author, or (b) could continue reading it through another site, such as MangaDex (I found [the same series on there](https://mangadex.org/title/3551/karakuri-d-ji-ultimo)).

As for fixing this:
1. Poketo can do a better job of showing what went wrong. I'll make a new issue to improve the error messages here.
2. I'd like to make Poketo correspond to where you're accessing it from; if you're reading from Europe, you shouldn't see an error intended for US viewers. This… is a much more difficult fix because of how web browsers work. It won't happen anytime soon.
