### ISSUE TITLE
Cannot read property of 'undefined'

### ISSUE THREAD

**Issue by Deterio** [poketo/poketo-reader#49]
Every time I delete a manga I get this error:
![error](https://i.imgur.com/fjcswWd.png)

After the refresh, everything works though and the manga is deleted.
I tried deleting all manga and now I get the error constantly even after refresh.

**Comment by rosszurowski** [comment]
Looks like there were two different issues:

* The "delete this bookmark?" panel had a bug.
* Poketo didn't have a way to handle collections without any bookmarks.

I just pushed a fix for both these problems (356ba50283335ea5ab7a5f92a9923de21e717ed9). Next time you open Poketo, you'll still get the same error because it's caching some bad data. Hit the "refresh" button on the error page (don't just refresh your browser) and that'll clear the cache. After that, you should be good to roll.

Thanks for reporting!
