### ISSUE TITLE
Error while loading app

### ISSUE THREAD

**Issue by janowskima** [poketo/poketo-reader#52]
Hi,

I've recently been encountering a problem while loading Poketo; the loading "circle" is turning all the time, and finally it results in an "UNKNOWN ERROR". The only help for this is logging out and logging in - however, it only works once, after that it goes back to the previous problem. 

Any ideas?

**Comment by rosszurowski** [comment]
Sorry for the troubles! There's a few big issues plaguing Poketo at the moment that I haven't had much time to look at.

1. The database running the accounts sometimes gets overloaded with requests, which is what would logging in to not work. I'm just using a free database host right now, but perhaps I should look into a better one…
2. Mangadex recently added Cloudflare to their site, which blocks scraping requests about 50% of the time. There are techniques to get around it, but it'll take some time to figure out.

If you could send a screenshot of the error, that'd be handy, just to make sure I know exactly what's going wrong.

In the next few days I'll try setting up a new database to avoid these issues.

Thanks, as always, for reporting this.

**Comment by rosszurowski** [comment]
Ok, I just moved the database to a better service (Heroku, rather than ElephantSQL for the curious) so the log in issue should be gone. Please let me know if you're still seeing that.

This doesn't fix Mangadex series not loading. If you open the library and see a lot of blank images and get "an unknown error occurred" when trying to load a series — that's likely a Mangadex failure. I'll work on fixing that soon.

**Comment by janowskima** [comment]
Hey,

it's been happening again, the ERROR UNKOWN messages. It started appearing after I got the e-mail notification about some updates. Can't say more than that, sorry.
