### ISSUE TITLE
Unknown error again

### ISSUE THREAD

**Issue by janowskima** [poketo/poketo-reader#56]
Hi,

there's an unknown error while loading the app, I'm afraid there's nothing more I can add

**Comment by rosszurowski** [comment]
Hi! Sorry, this was another database error. The database host I'm using switched something up on me so Poketo couldn't load bookmarks. Should be all resolved now, but let me know if you spot it again.

**Comment by janowskima** [comment]
Thanks for the swift reaction, everything looks great!

Do you take donations perhaps? I'm using Poketo on a daily basis, and would hate it if you had to drop the project :)

**Comment by rosszurowski** [comment]
I appreciate the offer, but I don't take donations and would rather avoid doing so for now. After all, there aren't any serious costs to Poketo — it's either free services or a $1/month utilities tied together. Keeping it online isn't really a financial question, but a time/interest one.

I _am_ committed to keeping Poketo going. I still use it on occasion, and want to make it better. And you continuing to use it, posting issues and suggestions contribute to that commitment.

It's been a little quiet lately simply because I haven't been reading much manga. Next time I get into a manga reading swing, I'll pick up development on some new features and fixes.

So no promises, but know that I'm still here.
